FORMAT: 1A
HOST: http://www.google.com

# IDB1
Notes API is a *short texts saving* service similar to its physical paper presence on your table.

# Group handles
Notes related resources of the **Notes API**

## Handle Collection [/handle]
### List all Notes [GET]
+ Response 200 (application/json)

        [{
          "id": 1, "name": "Jack"
        }, {
          "id": 2, "name": "Bill"
        }]

### Create a Note [POST]
+ Request (application/json)

        { "name": "Sam" }

+ Response 201 (application/json)

        { "id": 3, "name": "Sam" }
        



# Group hashtags
Notes related resources of the **Notes API**

## HashTags Collection [/hashtags]
### List all Notes [GET]
+ Response 200 (application/json)

        [{
          "id": 1, "name": "Heats Spurs"
        }, {
          "id": 2, "name": "WorldCup"
        }]

### Create a Note [POST]
+ Request (application/json)

        { "name": "NoMoreSports" }

+ Response 201 (application/json)

        { "id": 3, "name": "NoMoreSports" }
        


## HashTag [/hashtags/{name}]
Get all hashtags with certain name

+ Parameters
    + name (required, string, `WorldCup` ) ... Need to be the name of objects
    
### Retrieve a Hashtag [GET]
+ Response 200 (application/json)

    + Header

            X-My-Header: The Value

    + Body

            { "id": 2, "name":"WorldCup" }


## HashTag [/hashtags/{id}]
A single Note object with all its details

+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the Note to perform action with. Has example value.


### Update a Hashtag [PUT]
+ Request (application/json)

        { "title": "VideoGames" }

+ Response 201 (application/json)

        { "id": 3, "title": "VideoGames" }
        


### Retrieve a Hashtag [GET]
+ Response 200 (application/json)

    + Header

            X-My-Header: The Value

    + Body

            { "id": 2, "name":"WorldCup" }

### Remove a Hashtag [DELETE]
+ Response 204
